[project]
name = "scikit-lite"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.5",
    "pre-commit>=4.5.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.8",
]
